export const UI_COPY = {
  navigation: ["Overview", "Agents", "Sessions", "Flywheel"],
  navigationLabel: "Product navigation",
  readOnly: "Read-only",
  hero: {
    eyebrow: "AGENT OPERATIONS",
    title: "Agent Overview",
    description: "查看 Agent 运行状态、真实使用量和最近活动。",
    running: (count: number) => `${count} Agents 运行中`,
    attention: (count: number) => `${count} Agents 需要关注`,
    loading: "正在读取 Agent 状态",
  },
  summary: {
    eyebrow: "OPERATIONS",
    title: "Fleet Snapshot",
    metrics: ["Agents", "Online", "Total Conversations", "Last 7 Days"],
    updated: "最后更新",
    agentsHint: "已纳入 Platform",
    activeHint: (count: number) => `${count} Agents 最近有真实活动`,
    totalHint: "数据来自 Flywheel",
  },
  insights: {
    eyebrow: "USAGE",
    trend: "7-Day Trend",
    ranking: "Active Agents",
    rankingHint: "按真实对话排序",
    conversations: (count: string) => `${count} 次对话`,
    emptyTrend: "等待新的真实对话数据",
    emptyRanking: "近 7 天还没有真实对话",
  },
  agent: {
    sectionEyebrow: "CATALOG",
    sectionTitle: "Agents",
    fields: [
      "Total Conversations",
      "Last 7 Days",
      "Uptime",
      "Last Activity",
      "Recent",
    ],
    refresh: (count: number) => `${count} Agents · 每 10 秒自动刷新`,
    emptyRecent: "尚无真实对话记录",
  },
  states: {
    active: "Active",
    online: "Online",
    degraded: "Degraded",
    offline: "Offline",
    checking: "Checking",
  },
  failures: {
    platform: "Platform 接口暂不可用，显示最后一次成功数据并继续重试。",
    usage: "Flywheel 暂不可用，显示最后一次成功数据；不使用模拟数据。",
    usageTitle: "对话数据暂不可用",
    usageDescription: "Agent 状态仍在更新，Platform 会继续尝试读取 Flywheel。",
  },
  loading: {
    title: "正在加载 Agent Overview",
    failedTitle: "暂时无法读取 Agent 数据",
    description: "正在汇总 Agent 状态和真实对话数据。",
    retry: "Platform 会继续自动重试。",
  },
  footer: "只读展示，不控制 Agent",
} as const;
