import { platformPath } from "./auth";
import type { HrCandidateDraft, HrContextVersion, HrDownloadTicket, HrPositionCandidate, HrPositionResources, HrTaskKind, HrTaskRecord } from "./hrR12Types";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export class HrR12ApiError extends Error { constructor(public readonly status: number, public readonly detail: unknown = null) { super(`HR R1.2 API ${status}`); this.name = "HrR12ApiError"; } }
function record(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === "object" && !Array.isArray(value); }
function id(value: string): string { if (!UUID.test(value)) throw new Error("HR R1.2 identifier invalid"); return value; }
async function request(path: string, init: RequestInit = {}): Promise<unknown> { const response = await fetch(platformPath(path), { credentials: "same-origin", headers: { Accept: "application/json", ...init.headers }, ...init }); if (!response.ok) { let detail: unknown = null; try { detail = await response.json(); } catch { /* opaque HTTP error */ } throw new HrR12ApiError(response.status, detail); } return response.json(); }
function mutation(csrfToken: string, requestId: string, body: unknown): RequestInit { id(requestId); return { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": csrfToken, "Idempotency-Key": requestId }, body: JSON.stringify(body) }; }
function resources(value: unknown): HrPositionResources { if (!record(value) || !Array.isArray(value.materials) || !Array.isArray(value.artifacts)) throw new Error("HR R1.2 resource response invalid"); const item = (raw: unknown, artifact = false) => { if (!record(raw) || typeof raw.attachment_id !== "string" || typeof raw.filename !== "string" || typeof raw.media_type !== "string" || typeof raw.state !== "string" || !Number.isSafeInteger(raw.size_bytes) || typeof raw.created_at !== "string" || typeof raw.preview_available !== "boolean" || typeof raw.download_available !== "boolean") throw new Error("HR R1.2 resource response invalid"); const base = { attachmentId: raw.attachment_id, filename: raw.filename, mediaType: raw.media_type, state: raw.state, sizeBytes: raw.size_bytes, createdAt: raw.created_at, sourceConversationId: typeof raw.source_conversation_id === "string" ? raw.source_conversation_id : null, sourceTurnId: typeof raw.source_turn_id === "string" ? raw.source_turn_id : null, previewAvailable: raw.preview_available, downloadAvailable: raw.download_available }; if (!artifact) return base; if (typeof raw.artifact_id !== "string" || !Number.isSafeInteger(raw.artifact_version)) throw new Error("HR R1.2 resource response invalid"); return { ...base, artifactId: raw.artifact_id, artifactVersion: raw.artifact_version }; }; return { materials: value.materials.map((raw) => item(raw)), artifacts: value.artifacts.map((raw) => item(raw, true)) } as HrPositionResources; }
function ticket(value: unknown): HrDownloadTicket { if (!record(value) || typeof value.content_path !== "string" || typeof value.expires_at !== "string") throw new Error("HR R1.2 ticket response invalid"); return { contentPath: value.content_path, expiresAt: value.expires_at }; }

export function createHrR12Api(csrfToken: string) {
  const path = (positionId: string, suffix = "") => `/api/hr/positions/${encodeURIComponent(id(positionId))}${suffix}`;
  const write = (positionId: string, suffix: string, requestId: string, body: unknown) => request(path(positionId, suffix), mutation(csrfToken, requestId, body));
  return {
    resources(positionId: string, signal?: AbortSignal): Promise<HrPositionResources> { return request(path(positionId, "/resources"), { signal }).then(resources); },
    downloadResource(positionId: string, attachmentId: string, requestId: string, purpose: "preview" | "download" = "download"): Promise<HrDownloadTicket> { return write(positionId, `/resources/${encodeURIComponent(id(attachmentId))}/ticket`, requestId, { purpose }).then(ticket); },
    context(positionId: string, signal?: AbortSignal): Promise<{ current: HrContextVersion | null; drafts: HrContextVersion[]; history: HrContextVersion[] }> { return request(path(positionId, "/context"), { signal }) as Promise<{ current: HrContextVersion | null; drafts: HrContextVersion[]; history: HrContextVersion[] }>; },
    confirmContext(positionId: string, contextVersionId: string, moduleKeys: string[], rowVersion: number, requestId: string): Promise<HrContextVersion> { return write(positionId, `/context/${encodeURIComponent(id(contextVersionId))}/confirm`, requestId, { module_keys: moduleKeys, expected_row_version: rowVersion }) as Promise<HrContextVersion>; },
    candidateDrafts(positionId: string, signal?: AbortSignal): Promise<HrCandidateDraft[]> { return request(path(positionId, "/candidate-drafts"), { signal }) as Promise<HrCandidateDraft[]>; },
    retryDraft(positionId: string, draftId: string, requestId: string): Promise<HrCandidateDraft> { return write(positionId, `/candidate-drafts/${encodeURIComponent(id(draftId))}/retry`, requestId, {}) as Promise<HrCandidateDraft>; },
    confirmDraft(positionId: string, draftId: string, requestId: string): Promise<HrPositionCandidate> { return write(positionId, `/candidate-drafts/${encodeURIComponent(id(draftId))}/confirm`, requestId, {}) as Promise<HrPositionCandidate>; },
    startTask(positionId: string, taskKind: HrTaskKind, requestId: string, input: { contextVersionId?: string; candidateIds?: string[]; materialIds?: string[]; feedback?: string } = {}): Promise<HrTaskRecord> { return write(positionId, "/tasks", requestId, { task_kind: taskKind, context_version_id: input.contextVersionId ?? null, candidate_ids: input.candidateIds ?? [], material_ids: input.materialIds ?? [], feedback: input.feedback ?? null }) as Promise<HrTaskRecord>; },
  };
}
export type HrR12Api = ReturnType<typeof createHrR12Api>;
