CREATE SCHEMA platform_hr_agent AUTHORIZATION CURRENT_USER;
REVOKE ALL ON SCHEMA platform_hr_agent FROM PUBLIC;
CREATE TABLE platform_hr_agent.threads (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), thread_id uuid PRIMARY KEY, sealed_title bytea NOT NULL, sealed_title_key_version integer NOT NULL CHECK (sealed_title_key_version > 0), CHECK ((sealed_title IS NULL) = (sealed_title_key_version IS NULL)), UNIQUE(owner_id,thread_id)
);
CREATE TABLE platform_hr_agent.works (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), work_id uuid PRIMARY KEY, thread_id uuid NOT NULL, input_revision bigint NOT NULL DEFAULT 1 CHECK(input_revision>0), state text NOT NULL CHECK(state IN ('queued','running','waiting_user','waiting_budget','completed','cancelled','failed','blocked')), phase text NOT NULL DEFAULT 'research' CHECK(phase IN ('research','finalizing')), answer_state text NOT NULL DEFAULT 'none' CHECK(answer_state IN ('none','partial','ended')), lease_epoch bigint NOT NULL DEFAULT 0 CHECK(lease_epoch>=0), lease_owner text, lease_until timestamptz, sealed_budget bytea NOT NULL, sealed_budget_key_version integer NOT NULL CHECK (sealed_budget_key_version > 0), CHECK ((sealed_budget IS NULL) = (sealed_budget_key_version IS NULL)), sealed_checkpoint bytea NOT NULL, sealed_checkpoint_key_version integer NOT NULL CHECK (sealed_checkpoint_key_version > 0), CHECK ((sealed_checkpoint IS NULL) = (sealed_checkpoint_key_version IS NULL)), budget_revision bigint NOT NULL DEFAULT 1 CHECK(budget_revision>0), last_event_seq bigint NOT NULL DEFAULT 0 CHECK(last_event_seq>=0), last_active_at timestamptz, UNIQUE(owner_id,work_id), FOREIGN KEY(owner_id,thread_id) REFERENCES platform_hr_agent.threads(owner_id,thread_id), CHECK((lease_owner IS NULL)=(lease_until IS NULL))
);
CREATE TABLE platform_hr_agent.inputs (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), work_id uuid NOT NULL, revision bigint NOT NULL CHECK(revision>0), input_id uuid NOT NULL UNIQUE, sealed_input bytea NOT NULL, sealed_input_key_version integer NOT NULL CHECK (sealed_input_key_version > 0), CHECK ((sealed_input IS NULL) = (sealed_input_key_version IS NULL)), objects jsonb NOT NULL CHECK(jsonb_typeof(objects)='array'), role_release text NOT NULL, role_manifest_sha text NOT NULL CHECK(role_manifest_sha ~ '^[a-f0-9]{64}$'), knowledge_release text NOT NULL, configuration_revision text NOT NULL, PRIMARY KEY(work_id,revision), UNIQUE(owner_id,work_id,revision), FOREIGN KEY(owner_id,work_id) REFERENCES platform_hr_agent.works(owner_id,work_id)
);
CREATE TABLE platform_hr_agent.model_attempts (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), attempt_id uuid PRIMARY KEY, work_id uuid NOT NULL, input_revision bigint NOT NULL, ordinal bigint NOT NULL CHECK(ordinal>0), purpose text NOT NULL CHECK(purpose IN ('work','summary')), logical_step_id uuid NOT NULL, retry_no integer NOT NULL CHECK(retry_no BETWEEN 0 AND 2), status text NOT NULL CHECK(status IN ('prepared','sending','committed','interrupted','failed','superseded')), usage_observation_id uuid, reported_usage_hash text, sealed_request bytea NOT NULL, sealed_request_key_version integer NOT NULL CHECK (sealed_request_key_version > 0), CHECK ((sealed_request IS NULL) = (sealed_request_key_version IS NULL)), sealed_reply bytea, sealed_reply_key_version integer CHECK (sealed_reply_key_version > 0), CHECK ((sealed_reply IS NULL) = (sealed_reply_key_version IS NULL)), provider_profile text NOT NULL, provider_request_id text, reserved_tokens bigint NOT NULL CHECK(reserved_tokens>=0), charged_tokens bigint NOT NULL DEFAULT 0 CHECK(charged_tokens>=0), raw_usage_cipher bytea, raw_usage_cipher_key_version integer CHECK (raw_usage_cipher_key_version > 0), CHECK ((raw_usage_cipher IS NULL) = (raw_usage_cipher_key_version IS NULL)), usage_quality text NOT NULL CHECK(usage_quality IN ('unknown','estimated','reported')), started_at timestamptz NOT NULL DEFAULT now(), ended_at timestamptz, UNIQUE(owner_id,attempt_id), UNIQUE(owner_id,work_id,input_revision,attempt_id), UNIQUE(work_id,ordinal), UNIQUE(work_id,input_revision,logical_step_id,retry_no), FOREIGN KEY(owner_id,work_id,input_revision) REFERENCES platform_hr_agent.inputs(owner_id,work_id,revision)
);
CREATE TABLE platform_hr_agent.operations (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), operation_id uuid PRIMARY KEY, work_id uuid, input_revision bigint, attempt_id uuid, slot integer CHECK(slot>=0), namespace text NOT NULL, request_key text NOT NULL, request_hash text NOT NULL CHECK(request_hash ~ '^[a-f0-9]{64}$'), status text NOT NULL CHECK(status IN ('prepared','committed','aborted')), sealed_arguments bytea NOT NULL, sealed_arguments_key_version integer NOT NULL CHECK (sealed_arguments_key_version > 0), CHECK ((sealed_arguments IS NULL) = (sealed_arguments_key_version IS NULL)), sealed_receipt bytea, sealed_receipt_key_version integer CHECK (sealed_receipt_key_version > 0), CHECK ((sealed_receipt IS NULL) = (sealed_receipt_key_version IS NULL)), lease_epoch bigint, UNIQUE(owner_id,operation_id), UNIQUE(owner_id,namespace,request_key), UNIQUE(attempt_id,slot), FOREIGN KEY(owner_id,work_id) REFERENCES platform_hr_agent.works(owner_id,work_id), FOREIGN KEY(owner_id,attempt_id) REFERENCES platform_hr_agent.model_attempts(owner_id,attempt_id), CHECK((attempt_id IS NULL)=(slot IS NULL)), CHECK(attempt_id IS NULL OR (work_id IS NOT NULL AND input_revision IS NOT NULL AND lease_epoch IS NOT NULL)), FOREIGN KEY(owner_id,work_id,input_revision,attempt_id) REFERENCES platform_hr_agent.model_attempts(owner_id,work_id,input_revision,attempt_id)
);
CREATE TABLE platform_hr_agent.entries (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), entry_id uuid PRIMARY KEY, work_id uuid NOT NULL, input_revision bigint NOT NULL, seq bigint NOT NULL CHECK(seq>0), kind text NOT NULL CHECK(kind IN ('user','assistant','tool','note','question','summary')), objects jsonb NOT NULL CHECK(jsonb_typeof(objects)='array'), local_work_id uuid, sealed_body bytea NOT NULL, sealed_body_key_version integer NOT NULL CHECK (sealed_body_key_version > 0), CHECK ((sealed_body IS NULL) = (sealed_body_key_version IS NULL)), source_refs jsonb NOT NULL CHECK(jsonb_typeof(source_refs)='array'), sealed_summary_provenance bytea, sealed_summary_provenance_key_version integer CHECK (sealed_summary_provenance_key_version > 0), CHECK ((sealed_summary_provenance IS NULL) = (sealed_summary_provenance_key_version IS NULL)), model_attempt_id uuid, operation_id uuid, UNIQUE(work_id,seq), FOREIGN KEY(owner_id,work_id,input_revision) REFERENCES platform_hr_agent.inputs(owner_id,work_id,revision), FOREIGN KEY(owner_id,model_attempt_id) REFERENCES platform_hr_agent.model_attempts(owner_id,attempt_id), FOREIGN KEY(owner_id,operation_id) REFERENCES platform_hr_agent.operations(owner_id,operation_id), CHECK((kind='summary')=(sealed_summary_provenance IS NOT NULL))
);
CREATE TABLE platform_hr_agent.read_records (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), read_id uuid PRIMARY KEY, work_id uuid NOT NULL, input_revision bigint NOT NULL, operation_id uuid NOT NULL UNIQUE, ref jsonb NOT NULL, start_offset bigint NOT NULL CHECK(start_offset>=0), end_offset bigint NOT NULL, total_characters bigint NOT NULL, objects jsonb NOT NULL, CHECK(start_offset<=end_offset AND end_offset<=total_characters), FOREIGN KEY(owner_id,work_id,input_revision) REFERENCES platform_hr_agent.inputs(owner_id,work_id,revision), FOREIGN KEY(owner_id,operation_id) REFERENCES platform_hr_agent.operations(owner_id,operation_id)
);
CREATE TABLE platform_hr_agent.events (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), work_id uuid NOT NULL, seq bigint NOT NULL CHECK(seq>0), input_revision bigint NOT NULL, type text NOT NULL CHECK(type IN ('accepted','input_changed','started','progress','model_committed','tool_finished','result_saved','question_opened','budget_changed','state_changed','tool_error','recovery_started','context_compacted')), state text NOT NULL CHECK(state IN ('queued','running','waiting_user','waiting_budget','completed','cancelled','failed','blocked')), phase text NOT NULL CHECK(phase IN ('research','finalizing')), error_code text, error_retryable boolean, tool_status text, result_ref jsonb, PRIMARY KEY(work_id,seq), FOREIGN KEY(owner_id,work_id,input_revision) REFERENCES platform_hr_agent.inputs(owner_id,work_id,revision)
);
CREATE TABLE platform_hr_agent.results (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), result_id uuid PRIMARY KEY, origin_work_id uuid NOT NULL, current_revision uuid NOT NULL, kind text NOT NULL, UNIQUE(owner_id,result_id), FOREIGN KEY(owner_id,origin_work_id) REFERENCES platform_hr_agent.works(owner_id,work_id)
);
CREATE TABLE platform_hr_agent.result_revisions (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), revision_id uuid PRIMARY KEY, result_id uuid NOT NULL, sealed_document bytea NOT NULL, sealed_document_key_version integer NOT NULL CHECK (sealed_document_key_version > 0), CHECK ((sealed_document IS NULL) = (sealed_document_key_version IS NULL)), sha256 text NOT NULL CHECK(sha256 ~ '^[a-f0-9]{64}$'), objects jsonb NOT NULL, created_by_operation uuid NOT NULL UNIQUE, UNIQUE(owner_id,result_id,revision_id), FOREIGN KEY(owner_id,result_id) REFERENCES platform_hr_agent.results(owner_id,result_id), FOREIGN KEY(owner_id,created_by_operation) REFERENCES platform_hr_agent.operations(owner_id,operation_id)
);
CREATE TABLE platform_hr_agent.result_links (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), result_id uuid NOT NULL, object_kind text NOT NULL CHECK(object_kind IN ('position','candidate','company','topic')), object_id text NOT NULL, linked_by_operation uuid NOT NULL, PRIMARY KEY(result_id,object_kind,object_id), FOREIGN KEY(owner_id,result_id) REFERENCES platform_hr_agent.results(owner_id,result_id), FOREIGN KEY(owner_id,linked_by_operation) REFERENCES platform_hr_agent.operations(owner_id,operation_id)
);
CREATE TABLE platform_hr_agent.standards (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), position_id uuid NOT NULL, current_revision uuid NOT NULL, PRIMARY KEY(owner_id,position_id)
);
CREATE TABLE platform_hr_agent.standard_revisions (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), revision_id uuid PRIMARY KEY, position_id uuid NOT NULL, previous_revision uuid, sealed_items bytea NOT NULL, sealed_items_key_version integer NOT NULL CHECK (sealed_items_key_version > 0), CHECK ((sealed_items IS NULL) = (sealed_items_key_version IS NULL)), proposal_ref jsonb NOT NULL, selected_change_ids jsonb NOT NULL, confirmed_by uuid NOT NULL CHECK(confirmed_by=owner_id), created_by_operation uuid NOT NULL UNIQUE, UNIQUE(owner_id,position_id,revision_id), FOREIGN KEY(owner_id,created_by_operation) REFERENCES platform_hr_agent.operations(owner_id,operation_id), FOREIGN KEY(owner_id,position_id,previous_revision) REFERENCES platform_hr_agent.standard_revisions(owner_id,position_id,revision_id)
);
CREATE TABLE platform_hr_agent.reference_edges (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), dependent_kind text NOT NULL, dependent_id text NOT NULL, dependent_revision text NOT NULL, source_kind text NOT NULL, source_id text NOT NULL, source_revision text NOT NULL, source_sha256 text NOT NULL CHECK(source_sha256 ~ '^[a-f0-9]{64}$'), PRIMARY KEY(owner_id,dependent_kind,dependent_id,dependent_revision,source_kind,source_id,source_revision), CHECK((dependent_kind,dependent_id,dependent_revision)<>(source_kind,source_id,source_revision))
);
CREATE TABLE platform_hr_agent.budget_extensions (
owner_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), extension_id uuid PRIMARY KEY, work_id uuid NOT NULL, budget_revision bigint NOT NULL CHECK(budget_revision>1), addition jsonb NOT NULL CHECK(jsonb_typeof(addition)='object' AND addition ?& ARRAY['model_calls','total_tokens','active_seconds'] AND jsonb_typeof(addition->'model_calls')='number' AND jsonb_typeof(addition->'total_tokens')='number' AND jsonb_typeof(addition->'active_seconds')='number' AND (addition->>'model_calls')::bigint>=0 AND (addition->>'total_tokens')::bigint>=0 AND (addition->>'active_seconds')::numeric>=0 AND ((addition->>'model_calls')::bigint>0 OR (addition->>'total_tokens')::bigint>0 OR (addition->>'active_seconds')::numeric>0)), reason_cipher bytea NOT NULL, reason_cipher_key_version integer NOT NULL CHECK (reason_cipher_key_version > 0), CHECK ((reason_cipher IS NULL) = (reason_cipher_key_version IS NULL)), created_by_operation uuid NOT NULL UNIQUE, UNIQUE(work_id,budget_revision), FOREIGN KEY(owner_id,work_id) REFERENCES platform_hr_agent.works(owner_id,work_id), FOREIGN KEY(owner_id,created_by_operation) REFERENCES platform_hr_agent.operations(owner_id,operation_id)
);
ALTER TABLE platform_hr_agent.results ADD FOREIGN KEY(owner_id,result_id,current_revision) REFERENCES platform_hr_agent.result_revisions(owner_id,result_id,revision_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE platform_hr_agent.standards ADD FOREIGN KEY(owner_id,position_id,current_revision) REFERENCES platform_hr_agent.standard_revisions(owner_id,position_id,revision_id) DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX hr_agent_threads_page ON platform_hr_agent.threads(owner_id,created_at,thread_id);
CREATE INDEX hr_agent_works_page ON platform_hr_agent.works(owner_id,thread_id,created_at,work_id);
CREATE INDEX hr_agent_claim ON platform_hr_agent.works(state,lease_until,created_at);
CREATE UNIQUE INDEX hr_agent_entry_projection ON platform_hr_agent.entries(kind,model_attempt_id) WHERE kind IN ('assistant','summary');
CREATE INDEX hr_agent_result_object ON platform_hr_agent.result_links(owner_id,object_kind,object_id);
CREATE INDEX hr_agent_source_edges ON platform_hr_agent.reference_edges(owner_id,source_kind,source_id,source_revision);
REVOKE ALL ON ALL TABLES IN SCHEMA platform_hr_agent FROM PUBLIC;
DO $$ DECLARE app_role text; BEGIN
 app_role := CASE current_user WHEN 'platform_control_owner' THEN 'platform_control_app' WHEN 'platform_control_owner_preview' THEN 'platform_control_app_preview' ELSE NULL END;
 IF app_role IS NULL THEN RAISE EXCEPTION 'unsupported HR migration owner'; END IF;
 EXECUTE format('GRANT USAGE ON SCHEMA platform_hr_agent TO %I', app_role);
 EXECUTE format('GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA platform_hr_agent TO %I', app_role);
 EXECUTE format('REVOKE UPDATE ON platform_hr_agent.inputs, platform_hr_agent.entries, platform_hr_agent.result_revisions, platform_hr_agent.standard_revisions, platform_hr_agent.reference_edges, platform_hr_agent.budget_extensions, platform_hr_agent.read_records, platform_hr_agent.events FROM %I', app_role);
END $$;
