import type { FaeAnalysisReport } from "../faeReportTypes";


export const reportFixture: FaeAnalysisReport = {
  schema_name: "fae.analysis-report",
  schema_version: "1.0.0",
  report_id: "fae-topic-production-outcome",
  report_version: 1,
  report_type: "topic",
  status: "ready",
  title: "FAE Agent 生产成果",
  period: {
    start_at: "2026-07-01T00:00:00Z",
    end_at: "2026-08-31T00:00:00Z",
  },
  data_cutoff_at: "2026-08-31T00:00:00Z",
  generated_at: "2026-08-31T08:00:00Z",
  analysis_version: "v5",
  source: {
    agent_id: "ai-fae-agent",
    source_kind: "fae",
    environment: "production",
    source_snapshot_at: "2026-08-31T00:00:00Z",
    session_count: 692,
    turn_count: 1492,
    feedback_event_count: 126,
    reviewed_session_count: 654,
  },
  summary: {
    headline: "FAE Agent 已形成可持续复审的生产服务能力",
    overview: "基于真实生产会话和独立复审形成的冻结成果。",
    top_finding_ids: ["finding-1"],
    top_recommendation_ids: ["rec-1"],
  },
  metrics: [
    {
      metric_id: "value.observed_included_sessions",
      dimension: "usage",
      label: "累计服务会话",
      value: 692,
      unit: "count",
      numerator: null,
      denominator: null,
      filters: ["population=included"],
      assumptions: [],
      evidence_artifact_refs: ["metrics.json"],
    },
    {
      metric_id: "product.family_counts_public",
      dimension: "usage",
      label: "高频产品族",
      value: { Gemini: 326, Femto: 103, Oradar: "少于 5" },
      unit: "distribution",
      numerator: null,
      denominator: 692,
      filters: [],
      assumptions: [],
      evidence_artifact_refs: ["metrics.json"],
    },
    {
      metric_id: "value.assisted_reviewed_sessions",
      dimension: "business_value",
      label: "已形成 FAE 辅助价值的会话",
      value: 179,
      unit: "count",
      numerator: null,
      denominator: null,
      filters: ["independent_review=accepted"],
      assumptions: [],
      evidence_artifact_refs: ["metrics.json"],
    },
    {
      metric_id: "value.scenario_potential_conversion_sessions",
      dimension: "business_value",
      label: "潜在可转化会话",
      value: 216,
      unit: "count",
      numerator: null,
      denominator: null,
      filters: ["fully_resolved=false"],
      assumptions: [],
      evidence_artifact_refs: ["metrics.json"],
    },
    {
      metric_id: "quality.reviewed_fully_resolved_rate",
      dimension: "answer_effectiveness",
      label: "完全解决率",
      value: 0.36,
      unit: "ratio",
      numerator: 36,
      denominator: 100,
      filters: [],
      assumptions: [],
      evidence_artifact_refs: ["metrics.json"],
    },
    {
      metric_id: "feedback.canonical_issues",
      dimension: "insights_improvement",
      label: "受治理根因家族",
      value: 15,
      unit: "count",
      numerator: null,
      denominator: null,
      filters: [],
      assumptions: [],
      evidence_artifact_refs: ["metrics.json"],
    },
  ],
  findings: [
    {
      finding_id: "finding-1",
      dimension: "insights_improvement",
      severity: "high",
      title: "资料缺口",
      description: "识别到高频资料问题。",
      root_cause_hypothesis: "资料分散。",
      impact_scope: "技术支持。",
      metric_ids: ["feedback.canonical_issues"],
      evidence_refs: [],
      recommendation_ids: ["rec-1"],
      linked_issue_ids: [],
    },
  ],
  recommendations: [
    {
      recommendation_id: "rec-1",
      dimension: "insights_improvement",
      priority: "p1",
      title: "补齐资料",
      rationale: "减少重复咨询。",
      proposed_action: "建设统一资料入口。",
      owner_role: "FAE",
      finding_ids: ["finding-1"],
      success_metric_ids: ["feedback.canonical_issues"],
    },
  ],
  cases: [],
  failure: null,
  publication: {
    payload_digest: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    imported_at: "2026-08-31T09:00:00Z",
  },
  latest_source_sync_at: "2026-09-01T00:00:00Z",
  currentness: "source_updated",
};
