from __future__ import annotations

from .models import validate_panorama


def _node(
    id: str,
    title: str,
    subtitle: str,
    detail: list[str],
    *,
    actions: list[str] | None = None,
    sources: list[str] | None = None,
):
    return {
        "id": id,
        "title": title,
        "subtitle": subtitle,
        "detail": detail,
        "actions": actions or [],
        "source_ids": sources or ["pan-domains"],
    }


PANORAMA_SEED = validate_panorama(
    {
        "version": "2026-09-20.seed.1",
        "updated_at": "2026-09-20T00:00:00Z",
        "title": "奥比中光 AI 工程全景",
        "layers": [
            {
                "id": "industry",
                "title": "产业位置",
                "kind": "industry",
                "groups": [
                    {
                        "id": "industry-upstream",
                        "title": "上游供给",
                        "role": "upstream",
                        "columns": 1,
                        "node_ids": ["semiconductor", "optoelectronics", "precision"],
                    },
                    {
                        "id": "industry-company",
                        "title": "奥比中光",
                        "role": "company",
                        "columns": 1,
                        "node_ids": ["orbbec"],
                    },
                    {
                        "id": "industry-downstream",
                        "title": "行业应用",
                        "role": "downstream",
                        "columns": 3,
                        "node_ids": [
                            "robotics",
                            "scanning",
                            "biometrics",
                            "measurement",
                            "aiot",
                        ],
                    },
                ],
            },
            {
                "id": "portfolio",
                "title": "产品与技术",
                "kind": "portfolio",
                "groups": [
                    {
                        "id": "portfolio-products",
                        "title": "产品布局",
                        "role": "products",
                        "columns": 6,
                        "node_ids": [
                            "chip-product",
                            "camera",
                            "lidar",
                            "smart-vision",
                            "industry-systems",
                            "software",
                        ],
                    },
                    {
                        "id": "portfolio-technology",
                        "title": "共用技术",
                        "role": "technology",
                        "columns": 5,
                        "node_ids": [
                            "chip-tech",
                            "optics",
                            "depth-algorithm",
                            "sdk-tech",
                            "calibration",
                        ],
                    },
                ],
            },
            {
                "id": "workflow",
                "title": "Marketing ↔ Technology",
                "kind": "workflow",
                "groups": [
                    {
                        "id": "workflow-marketing",
                        "title": "Marketing",
                        "role": "marketing",
                        "columns": 5,
                        "node_ids": [
                            "market-insight",
                            "requirements",
                            "product-planning",
                            "marketing-sales",
                            "customer-use",
                        ],
                    },
                    {
                        "id": "workflow-delivery",
                        "title": "Technology",
                        "role": "delivery",
                        "columns": 5,
                        "node_ids": [
                            "research",
                            "feasibility",
                            "development",
                            "manufacturing",
                            "integration",
                        ],
                    },
                ],
            },
            {
                "id": "support",
                "title": "支撑体系",
                "kind": "support",
                "groups": [
                    {
                        "id": "support-shared",
                        "title": "全公司共用能力",
                        "role": "support",
                        "columns": 8,
                        "node_ids": [
                            "talent",
                            "finance",
                            "procurement",
                            "quality",
                            "legal",
                            "digital",
                            "projects",
                            "office",
                        ],
                    },
                ],
            },
        ],
        "nodes": [
            _node(
                "semiconductor",
                "半导体制造",
                "芯片与器件供给",
                ["上游产业位置，不表示指定供应商。"],
            ),
            _node(
                "optoelectronics",
                "光电器件",
                "光学与光电器件",
                ["光学料件与器件边界需按产品核实。"],
            ),
            _node(
                "precision",
                "光学与精密制造",
                "制造与装配能力",
                ["制造、装配和测试边界需内部资料确认。"],
            ),
            _node(
                "orbbec",
                "奥比中光",
                "3D 视觉感知技术与产品",
                ["公司处于上游供给与行业应用之间。"],
                sources=["product-inventory"],
            ),
            _node(
                "robotics",
                "机器人",
                "代表行业应用",
                ["代表关系以 Gemini 330 与 SDK／ROS 2 为例，不概括全部适配。"],
                sources=["product-solutions", "gemini-330"],
            ),
            _node(
                "scanning",
                "三维扫描",
                "成像与重建",
                ["场景来自公开方案分类。"],
                sources=["product-solutions"],
            ),
            _node(
                "biometrics",
                "生物识别",
                "身份与交互",
                ["场景来自公开方案分类。"],
                sources=["product-solutions"],
            ),
            _node(
                "measurement",
                "工业三维测量",
                "测量与验收",
                ["产品规格、标定条件与验收需分别核实。"],
                sources=["product-solutions"],
            ),
            _node(
                "aiot",
                "AIoT",
                "空间感知与智能设备",
                ["场景来自公开方案分类。"],
                sources=["product-solutions"],
            ),
            _node(
                "chip-product",
                "芯片",
                "LS635 等雷达传感器芯片",
                ["芯片交付与深度引擎技术分别表达。"],
                sources=["product-inventory"],
            ),
            _node(
                "camera",
                "视觉模组与相机",
                "Gemini、Femto、Astra、DaBai、Physis",
                ["型号、接口、固件和 SDK 组合需逐项核实。"],
                sources=["product-inventory", "gemini-330"],
            ),
            _node(
                "lidar",
                "激光雷达",
                "Pulsar、MS 等产品族",
                ["产品族来自公开产品底稿。"],
                sources=["product-inventory"],
            ),
            _node(
                "smart-vision",
                "智能视觉设备",
                "Persee、数据采集硬件平台",
                ["设备与服务交付边界需按产品核实。"],
                sources=["product-inventory"],
            ),
            _node(
                "industry-systems",
                "行业终端与系统",
                "支付终端与工业测量系统",
                ["包括 XTOM、XTDIC、Tube Qualify 等公开条目。"],
                sources=["product-inventory"],
            ),
            _node(
                "software",
                "软件与算法",
                "SDK、深度增强与开发工具",
                ["SDK 支持受型号、固件、主机和系统约束。"],
                actions=["notes"],
                sources=["product-inventory", "ros2"],
            ),
            _node(
                "chip-tech",
                "自研芯片",
                "深度计算与 ASIC",
                ["技术维度不等同于单一产品线。"],
                sources=["product-tech"],
            ),
            _node(
                "optics",
                "光学感知",
                "结构光、双目、iToF、dToF",
                ["感知原理与深度计算芯片是不同维度。"],
                sources=["product-tech"],
            ),
            _node(
                "depth-algorithm",
                "深度算法",
                "深度计算与后处理",
                ["算法能力需结合产品与版本资料核实。"],
                sources=["product-tech"],
            ),
            _node(
                "sdk-tech",
                "固件与 SDK",
                "固件、SDK、ROS 与主机",
                ["共用软件能力按明确关系连接产品。"],
                actions=["notes"],
                sources=["product-tech", "ros2"],
            ),
            _node(
                "calibration",
                "标定与量产",
                "工程、量产与质量验证",
                ["标定条件与质量结果需保留来源。"],
                sources=["product-tech"],
            ),
            _node(
                "market-insight",
                "市场洞察",
                "行业、竞争与客户分层",
                ["洞察进入需求与产品规划。"],
            ),
            _node(
                "requirements",
                "需求定义",
                "需求收集、澄清与排序",
                ["关联需要人工确认。"],
            ),
            _node(
                "product-planning",
                "产品规划",
                "定义、定位与路线",
                ["不以节点面积表示优先级。"],
            ),
            _node(
                "marketing-sales",
                "推广销售",
                "价值沟通、渠道与伙伴",
                ["商业化反馈回到产品与技术。"],
            ),
            _node(
                "customer-use",
                "客户应用",
                "使用反馈与需求闭环",
                ["VOC 是独立入口，沿用原权限。"],
                actions=["voc"],
                sources=["asset-voc"],
            ),
            _node(
                "research",
                "技术预研",
                "技术路线与能力积累",
                ["研究技术路线、原理与关键能力。"],
            ),
            _node(
                "feasibility",
                "场景验证",
                "方案、样机与风险验证",
                ["在目标场景验证方案与关键约束。"],
            ),
            _node(
                "development",
                "研发验证",
                "软硬件设计、实现与测试",
                ["覆盖软硬件研发、测试与设计验证。"],
            ),
            _node(
                "manufacturing",
                "量产交付",
                "试产、制造、标定与质量",
                ["连接试产转产、制造标定与交付。"],
            ),
            _node(
                "integration",
                "集成服务",
                "设计导入与现场支持",
                ["支持客户集成、现场问题与产品迭代。"],
                actions=["fae"],
                sources=["asset-fae"],
            ),
            _node(
                "talent",
                "组织人才",
                "招聘、盘点、培养与配置",
                ["招聘、人才盘点、能力画像、培养、人员配置与梯队建设。"],
                actions=["hr"],
                sources=["asset-hr"],
            ),
            _node(
                "finance",
                "财务经营",
                "预算、成本、核算与经营分析",
                ["详情可承载职能说明，主图不展示经营数字。"],
            ),
            _node(
                "procurement",
                "采购供应",
                "供应商、物料、产能与物流",
                ["供应关系需有依据后连接。"],
            ),
            _node(
                "quality",
                "质量管理",
                "研发、制造、可靠性与客诉",
                ["研发质量、来料与制造质量、可靠性、客诉闭环与质量体系。"],
            ),
            _node(
                "legal",
                "法务与知识产权",
                "合同、专利、许可与合规",
                ["合同、专利、软件许可、商业秘密与合规管理。"],
            ),
            _node(
                "digital",
                "数字化与知识",
                "系统、数据、知识、身份与 AI 平台",
                ["平台动作保留各自原权限。"],
                actions=[
                    "brain",
                    "agents",
                    "missions",
                    "sessions",
                    "operations",
                    "review",
                    "activity",
                    "identity",
                    "governance",
                    "access",
                    "account",
                    "agent-admin",
                    "notes",
                ],
            ),
            _node(
                "projects",
                "项目协同",
                "组合、计划、资源、评审与变更",
                ["项目关系有依据后再连接。"],
            ),
            _node(
                "office",
                "行政保障",
                "空间、资产、差旅与日常事务",
                ["行政服务是独立入口，沿用原权限。"],
                actions=["office"],
                sources=["asset-admin"],
            ),
        ],
        "edges": [
            {
                "id": "camera-robotics",
                "from": "camera",
                "to": "robotics",
                "kind": "supply",
                "label": "Gemini 330",
            },
            {
                "id": "software-robotics",
                "from": "software",
                "to": "robotics",
                "kind": "supports",
                "label": "SDK／ROS 2",
            },
            {
                "id": "chip-camera",
                "from": "chip-tech",
                "to": "camera",
                "kind": "supports",
                "label": "深度引擎",
            },
            {
                "id": "optics-camera",
                "from": "optics",
                "to": "camera",
                "kind": "supports",
                "label": "光学能力",
            },
            {
                "id": "sdk-software",
                "from": "sdk-tech",
                "to": "software",
                "kind": "supports",
                "label": "SDK 与平台适配",
            },
            {
                "id": "customer-feedback",
                "from": "customer-use",
                "to": "requirements",
                "kind": "feedback",
                "label": "客户反馈",
            },
        ],
        "sources": [
            {"id": "pan-domains", "label": "全景领域卡", "document": "domains"},
            {
                "id": "product-inventory",
                "label": "产品族清单 §1、3",
                "document": "products",
            },
            {
                "id": "product-solutions",
                "label": "产品族清单 §4.2",
                "document": "products",
            },
            {"id": "product-tech", "label": "产品族清单 §4.1", "document": "products"},
            {
                "id": "gemini-330",
                "label": "Gemini 330 官方产品与审计资料",
                "document": "products",
            },
            {
                "id": "ros2",
                "label": "Orbbec SDK ROS 2 官方仓库",
                "document": "products",
            },
            {"id": "asset-hr", "label": "已有 AI 资产 §3.2", "document": "assets"},
            {"id": "asset-admin", "label": "已有 AI 资产 §3.3", "document": "assets"},
            {"id": "asset-fae", "label": "已有 AI 资产 §3.4", "document": "assets"},
            {"id": "asset-voc", "label": "已有 AI 资产 §3.5", "document": "assets"},
        ],
    }
)
